---
version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2182
      - ZOOKEEPER_CONNECTION_STRING=zookeeper:2182
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tinyurl
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
#       myslq dialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - db
      - zookeeper

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tinyurl
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--bind-address=0.0.0.0"]

  zookeeper:
    image: zookeeper
    ports:
      - "2182:2181"
    volumes:
      - zookeeper_data:/data


volumes:
    db_data:
    zookeeper_data:
